### ISSUE TITLE
Duplication with package.json?

### ISSUE THREAD

**Issue by dkniffin** [rails/importmap-rails#106]
I'm very new to the concept of importmaps, but I've gone through the readme and tried this gem out. A question I have is how this library works with `package.json` and `node_modules`. Doesn't `config/importmap.rb` duplicate information that is already stored in `package.json`? 

Or is the end-goal that we wouldn't need `package.json` at all? If the goal is to replace `package.json` and npm altogether, wouldn't this library end up being a full-fledged package manager?

**Comment by dkniffin** [comment]
And a related but different question: if I don't want to pull JS code from a CDN in production, am I required to commit my vendored code into my repo? Or is it possible to gitignore those files and have a command like `bin/importmap download-all` to pull down all code from the CDN?

**Comment by dhh** [comment]
importmap.rb is an alternative to package.json. You don't use node or npm directly when using import maps. If you don't rely on a CDN, you're supposed to checkin your vendored code in the repo. Otherwise the version won't be kept stable.
