### ISSUE TITLE
Unpredictable order in javascript_importmap_tags output with pin_all_from 

### ISSUE THREAD

**Issue by amcvitty** [rails/importmap-rails#108]
### What's the issue? 

We have a situation where Turbo is _sometimes_ invalidating the page and reloading after a form submission returns with 422 status (because of model validation errors). Like all the best bugs, this is only happening in production 😆. The impact is that instead of seeing the validation output around the form inputs, the data entered in the form is wiped when the form is refreshed.

rails (7.0.1)
turbo-rails (1.0.0)
importmap-rails (1.0.1)
Ruby 2.7.5

### Why is this related to importmap-rails?

Tracking the times it reloads the page vs when it successfully does a Turbo Drive page view, the only difference (aside from the CSRF tags) seems to be the content of the importmap script tag. Specifically, the order of the imports that use `pin_all_from` to load a whole directory.
<img width="1664" alt="Screenshot 2022-03-02 at 17 31 21" src="https://user-images.githubusercontent.com/7907585/156416001-f4725d92-3c46-4db9-84f5-ef8aaaaf4b3a.png">

### What should happen instead?

I believe the `pin_all_from` in the importmap should sort the results it gets from globbing the directory so that `javascript_importmap_tags` generates a consistent result.

I haven't actually been able to reproduce this in development. It seems to give a predictable ordering on my macbook, but not on heroku. I'm raising the issue now, because regardless of the specifics of our issue, making this output predictable seems like a good idea.

I'm open to submitting a PR if necessary here. I've already had a quick look at the code, but haven't cloned it to edit/run tests etc yet.

------

Everything below here is background information, so if you agree with the above, you probably don't have to read it!

### How do we know this is what's happening?

The Chrome DevTools show that the trigger for the reload is that Turbo is calling invalidate while rendering the 422 response.
![image](https://user-images.githubusercontent.com/7907585/156417271-2a50a8af-ff7c-45cf-94bb-5e6a5f5c7f27.png)

I poked around, and it looks like indeed the `Turbo.session.snapshot.headSnapshot.trackedElementSignature` is just a string with all of this in it. If this changes, then the page will reload. 
![Screenshot 2022-03-02 at 17 41 14](https://user-images.githubusercontent.com/7907585/156417715-d555b351-cd0f-4a3c-bd71-9fd0f9cb8c13.png)

I think it's not noticeable if the page occasionally reloads when navigating, but it's very noticeable when submitting a form, because it wipes the form content. 

#### Relevant bits of Turbo code showing that a change in this signature will reload the page.

https://github.com/hotwired/turbo/blob/56bfa462d598d6750386891efbbbfff7ebacb989/src/core/view.ts#L72
```
async render(renderer: R) {
  const { isPreview, shouldRender, newSnapshot: snapshot } = renderer

  if (shouldRender) {
	...
  } else {
	this.invalidate()
  }
```

https://github.com/hotwired/turbo/blob/539b249d82f44f5a4fd6bd245fe1e45718b31508/src/core/drive/page_renderer.ts#L5
```
export class PageRenderer extends Renderer<HTMLBodyElement, PageSnapshot> {
  get shouldRender() {
    return this.newSnapshot.isVisitable && this.trackedElementsAreIdentical
  }
```

https://github.com/hotwired/turbo/blob/539b249d82f44f5a4fd6bd245fe1e45718b31508/src/core/drive/page_renderer.ts#L52
```
  get trackedElementsAreIdentical() {
    return this.currentHeadSnapshot.trackedElementSignature == this.newHeadSnapshot.trackedElementSignature
  }
```

#### Our code
in layouts/admin_section.erb:
```
 <%= javascript_importmap_tags "admin_section" %>
```

in importmap.rb
```
pin "admin_section", preload: true
pin_all_from "app/javascript/admin", under: "admin"
pin_all_from "app/javascript/shared", under: "shared"

pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true

pin "jquery", to: "https://ga.jspm.io/npm:jquery@1.12.4/dist/jquery.js"
pin "jquery-ujs", to: "https://ga.jspm.io/npm:jquery-ujs@1.2.3/src/rails.js"

pin "jquery-ui", to: "jquery-ui.js"
pin "autocomplete-rails", to: "autocomplete-rails.js"
pin "bootstrap3", to: "https://ga.jspm.io/npm:bootstrap@3.3.7/dist/js/npm.js"
pin "bootstrap-tokenfield", to: "https://ga.jspm.io/npm:bootstrap-tokenfield@0.12.0/dist/bootstrap-tokenfield.js"

pin "cocoon"
```

in admin_section.js
```
// Activate Turbo:
import "@hotwired/turbo-rails";

// This shim imports jquery and puts it in the global scope
import "shared/jquery-shim";
// These modules depend on jQuery being in the global scope
import "jquery-ujs";
import "jquery-ui";
import "autocomplete-rails";
import "bootstrap3";
import "bootstrap-tokenfield";
import "cocoon";

import "admin/schedule";
import "shared/counter";
import "shared/autocompleteMap";
import "admin/booking_url";
import "admin/display_name";
import "admin/activity";
import "admin/venues";
import "shared/tag-token-picker";
import "shared/activate-tooltip";

console.log("Loaded admin_section.js");
```

**Comment by dhh** [comment]
I think you're right. Please do explore a PR to make sure things are sorted so they're consistent 👍
