### ISSUE TITLE
Filtering import maps

### ISSUE THREAD

**Issue by grncdr** [rails/importmap-rails#11]
As far as I can tell, importmap-rails has the same issue that I brought up over on https://github.com/rails/webpacker/issues/2876. To summarize, the importmap always exposes to the client the existence of _all_ javascript in the application.

For reference, my use case is a Rails monolith that is serving multiple apps/audiences. While nothing exactly _secret_ is contained in any of the JS, some of it (e.g. fetch calls revealing URLs that are not available to all users) would still be better left out.

While this library is still new, I'd like to suggest that adding some way of filtering the import map. The simplest way I can think of is providing an optional glob pattern to the view helpers. For example, writing `<%= javascript_importmap_tags(exclude: 'admin/**/*') %>` would ensure that nothing from `app/assets/javascript/admin` is included in the resulting import map.

What do you think?

**Comment by dhh** [comment]
If you need multiple import maps, you can manually instantiate different Map objects and pass those directly to the helpers. That’s all supported. Just that the out of the box setup is for the common case of one set of scripts.
