### ISSUE TITLE
Uncaught Error: Unable to resolve specifier

### ISSUE THREAD

**Issue by john-999** [rails/importmap-rails#118]
With the following setup:
```
# config/importmap.rb
pin_all_from "app/javascript/custom/global", under: "global"

# app/javascript/application.js
import "global"
```
...and a couple of .js files in the folder `app/javascript/custom/global`, I get the error:

**Uncaught Error: Unable to resolve specifier 'global' imported from http://[::1]:3000/assets/application-b202eb3d96ab4318d578d27457092b8fe389cfd22cc8edc819b1a0050fd4ce71.js**

Environment:
```
Rails: 7.0.2.3
gem "importmap-rails": 1.0.3
Firefox: 98.0.2
```

EDIT: A similar error here: https://stackoverflow.com/questions/70969937/rails-7-import-maps-import-folder-with-custom-scripts

**Comment by MeterSoft** [comment]
@john-999 hi, you should create index.js under custom folder some as in controllers folder

**Comment by dhh** [comment]
Feel free to open a PR for a doc change 👍
