### ISSUE TITLE
Importing submodules

### ISSUE THREAD

**Issue by sheff3rd** [rails/importmap-rails#123]
With the following setup:
```ruby
# config/importmap.rb
pin "three", to: "https://ga.jspm.io/npm:three@0.139.2/build/three.module.js"
```

import works great
```javascript
/* app/javascript/controllers/application.js */
import * as THREE from "three";

window.THREE = THREE;
```

but when I'm trying to import submodule
```javascript
/* app/javascript/controllers/application.js */
import Stats from "three/examples/jsm/libs/stats.module"
```

I get Uncaught TypeError
<img width="490" alt="image" src="https://user-images.githubusercontent.com/22118704/164559632-0e5c1d90-2ce1-44a4-a74f-ef65e332e013.png">

Is there something I am missing? I'm only starting with importmap and feeling pretty confident, but just can't figure this one out

**Comment by dhh** [comment]
Submodules are not supported as of now. You have to map those individually.

**Comment by guybedford** [comment]
Checked this case, and the subpath is definitely available on JSPM here - https://generator.jspm.io/#U2VhYGBiDs0rySzJSU1hKMkoSk11MNAzNLbUM0Ll6adWJOYW5KQW62cV5+rnZCYV6xeXJJYU6+Xmp5TmpOplFQMABnyN7kwA.

**Comment by dhh** [comment]
Ah yes. Remember now. Never ended up exploring an API for accessing this on the Ruby side.
