### ISSUE TITLE
Does importmap-rails not work with a Rails app that uses TypeScript?

### ISSUE THREAD

**Issue by heynan0** [rails/importmap-rails#124]
I'm working on a Rails application that was recently upgraded to version 7. I was looking to remove Webpacker, as it [is now "retired.](https://github.com/rails/webpacker/blob/14dcce2c23a207062e0fc4ebed6042381dabd66a/README.md)" I was ready to embrace `importmap-rails`, but then I realized that application uses TypeScript.

So in that case, would using `importmap-rails` not work? Is `importmap-rails` only intended for applications using JavaScript? What suggestion do you give for those that use TypeScript? https://github.com/rails/jsbundling-rails/ ? Is there a way to transpile the TypeScript and fit into the importmap pipeline or is that defeating its purpose?

**Comment by dhh** [comment]
Correct, import map serves the JavaScript directly without compilation. Typescript is compiled. So if you want TS, you'll need to use jsbundling-rails. Or you could of course also just switch from TS to regular JavaScript 👍

**Comment by rmacklin** [comment]
Another option is to use TypeScript through JSDoc comments:
https://www.typescriptlang.org/play#example/jsdoc-support
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html
