### ISSUE TITLE
How to access a JS library installed by importmap-rails from a Jest unit test

### ISSUE THREAD

**Issue by evgenyneu** [rails/importmap-rails#129]
I have a Rails 7 project, and in `importmap.rb` I have a Stimulus library:

```
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
```

I want to write a Jest  unit test for a Stimulus controller. In the unit test I import Stimulus `Application`:

```
import { Application } from '@hotwired/stimulus';
```

Of course, Jest shows error because it can not find `@hotwired/stimulus`, because it's not in `package.json`/`node_modules` (Jest was installed with Yarn). I can make the test work by installing `@hotwired/stimulus` with yarn:

```
yarn add @hotwired/stimulus --dev
```

But now I have Stimulus installed twice: fist via `importmap-rails` and second via yarn. Is there a way to have Stimulus installed just via `importmap-rails` and access the library from Jest tests without installing it with yarn?

P.S. I have Jest is installed with Yarn because I have legacy React code with jest tests.

**Comment by dhh** [comment]
If you need node anyway for the way you're developing, I don't think it makes sense to use import maps. Use jsbuilder-rails instead.

**Comment by schmijos** [comment]
I guess you mean "jsbundling-rails"?
