### ISSUE TITLE
Using a module from a script tag loaded with Turbo in shim mode

### ISSUE THREAD

**Issue by donv** [rails/importmap-rails#131]
Hi!

I have a page with a script tag that imports and uses jQuery defined in the import map.

```HTML
<script type="module">
import $ from "jquery";
$('#myElement').trigger('focus');
</script>
```

This works fine in all cases in Chrome and Firefox Nighly, and it works fine on a full load of the page in Firefox and Safari.  However, when I navigate to the page with Turbo, I get 

```
Uncaught TypeError: Error resolving module specifier “jquery”. Relative module specifiers must start with “./”, “../” or “/”.
```

Should this work?

**Comment by donv** [comment]
I am using

```
    rails (7.0.3)
    importmap-rails (1.1.0)
    turbo-rails (1.1.1)
```

Disabling Turbo is a current workaround.

**Comment by dhh** [comment]
Shim will be gone from version 2, so no longer relevant.
