### ISSUE TITLE
The resource http://localhost:3000/assets/es-module-shims.min-4213490297290a6ddf72ee4cafbf726e959de874.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

### ISSUE THREAD

**Issue by dorianmariefr** [rails/importmap-rails#133]
When I visit my application on Chrome 102 / macOS I get this warning:

> The resource http://localhost:3000/assets/es-module-shims.min-4213490297290a6ddf72ee4cafbf726e959de874.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

I'm not sure what the solution would be

**Comment by Brass-neck** [comment]
Is your application a Multi-page application ? I mean the webpack config has multi pages entry

**Comment by dhh** [comment]
Can't replicate. Sounds like maybe you've removed something from the default layout or you're not loading stimulus or turbo as is the default, and thus the import map is empty.

**Comment by dorianmariefr** [comment]
There is a delay between navigating the pages and Chrome showing the warning.

https://user-images.githubusercontent.com/58794487/174472968-9b4e0f42-fc28-4208-9def-205f7b6e22fd.mov

Here is a sample repository: https://github.com/dorianmariefr/rails-importmap-rails-issues-133

Here is my importmap:

```
    <script type="importmap" data-turbo-track="reload">{
  "imports": {
    "application": "/assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js",
    "@hotwired/turbo-rails": "/assets/turbo.min-e5023178542f05fc063cd1dc5865457259cc01f3fba76a28454060d33de6f429.js",
    "@hotwired/stimulus": "/assets/stimulus.min-900648768bd96f3faeba359cf33c1bd01ca424ca4d2d05f36a5d8345112ae93c.js",
    "@hotwired/stimulus-loading": "/assets/stimulus-loading-1fc59770fb1654500044afd3f5f6d7d00800e5be36746d55b94a2963a7a228aa.js",
    "controllers/hello_controller": "/assets/controllers/hello_controller-549135e8e7c683a538c3d6d517339ba470fcfb79d62f738a0a089ba41851a554.js",
    "controllers": "/assets/controllers/index-2db729dddcc5b979110e98de4b6720f83f91a123172e87281d5a58410fc43806.js",
    "controllers/application": "/assets/controllers/application-368d98631bccbf2349e0d4f8269afb3fe9625118341966de054759d96ea86c7e.js"
  }
}</script>
 ```

My application layout is pretty much the default one:

```erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClearanceTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p style="color:green"><%= notice %></p>
    <p style="color:red"><%= alert %></p>

    <%= yield %>
  </body>
</html>
```

**Comment by dhh** [comment]
Ah, either way, this is just a warning regarding preloading. You can turn that off if it bothers you.

**Comment by anguyen1181999** [comment]
Has the problem been resolved yet?
I'm having the same problem

**Comment by jubilee2** [comment]
```
javascript_importmap_tags shim: false 
```
it's works for me. I don't know what is function for shim for
