### ISSUE TITLE
Clarify what's happening with importing external libraries

### ISSUE THREAD

**Issue by davidkrider** [rails/importmap-rails#135]
I've been experimenting with using AgGrid with this new paradigm, and it seems to be missing a step. I found the answer at this [StackOverflow](https://stackoverflow.com/questions/70686825/how-access-js-function-using-import-maps-in-ruby-on-rails-7), but I don't understand why it worked. I should be able to do the following:

`bin/importmap pin ag-grid-community`

And then edit `application.js`:

> import "@hotwired/turbo-rails"
> import "controllers"
> import * as agGrid from "ag-grid-community"

And call it with `new agGrid.Grid(gridDiv, gridOptions);`

But this produces the error in the Chrome console: `Uncaught ReferenceError: agGrid is not defined`

However, adding `window.agGrid = agGrid` to `application.js` makes the whole thing work.

The question is why? Why should I have to use that `window` function to "export" the function to the browser? Isn't that the entire point of adding imports to the `application.js`?

Update: maybe I'm answering my own question. The Hotwire/turbo thing obviously works, so is the `application.js` file now just assumed to be working on the server side with the new JS setup? Do we need to explicitly "expose" includes in this file to the client side? And, if so, is there a way to do that only on the pages that need those specific functions, instead of doing it all at once in this file? Or would that introduce a bunch of complexity best avoided during the precompile?

**Comment by rafaelfranca** [comment]
This is how JavaScript module imports work. They are scoped to a single file, so if you import `agGrid` on application.js, you can only access that there. If you want to use `agGrid` in a file called `foo.js` you need to import it there, not in `application.js`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts

**Comment by davidkrider** [comment]
I see now. After pinning "ag-grid-community", I can import it in the script on the page. I don't need anything in application.js, but the tag needs to change in my .html.erb file, from `<%= javascript to %>` to `<script type="module">`.

```
<script type="module">

  import { Grid } from "ag-grid-community"

  var gridOptions = {
    columnDefs: [
      { headerName: 'Make', field: 'make' },
      { headerName: 'Model', field: 'model' },
      { headerName: 'Price', field: 'price' }
    ],
    rowData: [
      { make: 'Toyota', model: 'Celica', price: 35000 },
      { make: 'Ford', model: 'Mondeo', price: 32000 },
      { make: 'Porsche', model: 'Boxster', price: 72000 }
    ]
  }
  document.addEventListener('DOMContentLoaded', () => {
    const gridDiv = document.querySelector('#myGrid')
    new Grid(gridDiv, gridOptions)
  })

</script>
```
