### ISSUE TITLE
importmap command on windows "The term 'importmap" is not recognized

### ISSUE THREAD

**Issue by set-pfel** [rails/importmap-rails#149]
I have the gem "importmap-rails" installed 
bundle install

I see the file "C:\Ruby31-x64\lib\ruby\gems\3.1.0\gems\importmap-rails-1.1.5\lib\install\bin\importmap" but the .bat file is missing.

I tried removing and reinstalling the gem without success.

**Comment by dhh** [comment]
Use WSL 👍
