### ISSUE TITLE
pin_from_all, to: '.' does not work

### ISSUE THREAD

**Issue by mildred** [rails/importmap-rails#150]
When using pin_from_all to pin assets from the root under a different directory, there is an error in the importmap.

My configuration :

- `app/components` added to `Rails.application.config.assets.paths`
- app/assets linked from `app/assets/config/manifest.js` via `//= link_tree ../../components .js`

I have a file `app/components/tree_component_controller.js` that I want mapped to `components/tree_component_controller.js` but is compiled as an asset without the components prefix. I wish to use the `under` option to add this prefix via the `config/importmap.rb`:

```rb
pin_all_from 'app/components', under: 'components', to: '.'
```

It results in an error:

    Importmap skipped missing path: ./tree_component_controller.js

Instead, I'd like my importmap to contain

    "components/tree_component_controller": "/assets/tree_component_controller-3a05c789e09102f6ec41b4b60f66f2ff43a654e9cc2e8341912480a784d6a993.js"

I could make a monkey patch with:

```rb
class Importmap::Map
  module Extension
    def module_name_from(*args)
      super(*args).gsub(%r{^\./}, '')
    end

    def module_path_from(*args)
      super(*args).gsub(%r{^\./}, '')
    end
  end
  prepend Extension
end
```

to solve my problem

**Comment by javierg** [comment]
I had this same issue and setting to to an empty string resulted in the desired outcome:

`pin_all_from 'app/components', under: 'components', to: ''`

**Comment by dhh** [comment]
Feel free to document this with a doc PR.
