### ISSUE TITLE
Single-quoted strings in importmap.rb

### ISSUE THREAD

**Issue by nsilva-ta** [rails/importmap-rails#156]
Shouldn't we use single-quoted strings inside importmap.rb by default?

When there is a single-quoted string inside importmap.rb, as following example:
```ruby
pin 'jquery' # @3.4.1
```
the entry will be ignored when the command `./bin/importmap audit` is executed, and the vulnerability in the version of jquery is not reported.

**Comment by dhh** [comment]
Not a fan of single quotes. We've moved to double quotes everywhere. Sounds like it's a bug in the audit regexp not recognizing both. Do explore a fix to that 👍

**Comment by dkniffin** [comment]
The issue is on this line: https://github.com/rails/importmap-rails/blob/ad2cbb5994de7a3ff7d85d017489308bcdd738fd/lib/importmap/npm.rb#L56

It only checks for double-quotes. The regex needs to be updated to handle single quotes as well

**Comment by dhh** [comment]
Feel free to add a PR that also picks up single quotes for this.
