### ISSUE TITLE
Recovering from unpinned libraries

### ISSUE THREAD

**Issue by dvodvo** [rails/importmap-rails#161]
The default installation of a new rails 7 application has this `importmap`
```
# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
```
Adding libraries, particularly true with each of the [stimulus-components](https://www.stimulus-components.com/docs/stimulus-sortable/),  and the [stimulus-library](https://sub-xaero.github.io/stimulus-library/) may alter the default reference (to stimulus in these cases).  One notices overwriting, whether downloaded or not, and no preloading attribute, as:
```
pin "@hotwired/stimulus", to: "@hotwired--stimulus.js" # @3.1.1
pin "@hotwired/stimulus", to: "https://ga.jspm.io/npm:@hotwired/stimulus@3.1.1/dist/stimulus.js"
```
Remove the library (or component)
```
bin/importmap unpin stimulus-password-visibility
[...]
bin/importmap unpin stimulus-library
```
 now hotwired/stimulus is out of the importmap... 

Recovering from this is not transparent.
The [readMe installation instructions](https://github.com/rails/importmap-rails#installation) appear to be necessary to try and re-set to the default situation.  Faced with the problem of the importmap being altered in what would be a non-standard situation, 
```
1.  Run ./bin/bundle add importmap-rails
2.  Run ./bin/rails importmap:install
```
but this results in a different importmap.rb file:
```
pin "application", preload: true
pin "@hotwired/turbo-rails", to: "https://ga.jspm.io/npm:@hotwired/turbo-rails@7.2.4/app/javascript/turbo/index.js"
pin "@hotwired/turbo", to: "https://ga.jspm.io/npm:@hotwired/turbo@7.2.4/dist/turbo.es2017-esm.js"
pin "@rails/actioncable/src", to: "https://ga.jspm.io/npm:@rails/actioncable@7.0.4/src/index.js"
pin "@hotwired/stimulus", to: "https://ga.jspm.io/npm:@hotwired/stimulus@3.1.1/dist/stimulus.js"
```
turbo is added, stimulus loading is not. No preload defined.  Conclusion:  Not an avenue.

Having kept track of the importmap and is evolution (*that was not done with application.js*) the hope is a fallback situation of:
```
# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin "trix"
pin "@rails/actiontext", to: "actiontext.js"
```
When set this way, getting the json version of the importmap
```
bin/importmap json
{
  "imports": {
    "application": "/assets/application-3897b39d0f7fe7e947af9b84a1e1304bb30eb1dadb983104797d0a5e26a08736.js",
    "@hotwired/turbo-rails": "/assets/turbo.min-7ab2ea9f35bae4a4d65b552f9b93524099f267a8ba3a2e07002aaa7bff8ae4cf.js",
    "@hotwired/stimulus": "/assets/stimulus.min-2dae3fdcdb1a5ee8172d3dc02a2a10cd6d5f022cc7782b3888cedc06bab7388a.js",
    "@hotwired/stimulus-loading": "/assets/stimulus-loading-1fc59770fb1654500044afd3f5f6d7d00800e5be36746d55b94a2963a7a228aa.js",
    "trix": "/assets/trix-1563ff9c10f74e143b3ded40a8458497eaf2f87a648a5cbbfebdb7dec3447a5e.js",
    "@rails/actiontext": "/assets/actiontext-28c61f5197c204db043317a8f8826a87ab31495b741f854d307ca36122deefce.js",
    "controllers/application": "/assets/controllers/application-368d98631bccbf2349e0d4f8269afb3fe9625118341966de054759d96ea86c7e.js",
    "controllers/autogrow_controller": "/assets/controllers/autogrow_controller-cafab272b622b393bcc0400ee928b349b974c0ad4cb3d2e7ec6d6c219d91044c.js",
    "controllers/hello_controller": "/assets/controllers/hello_controller-549135e8e7c683a538c3d6d517339ba470fcfb79d62f738a0a089ba41851a554.js"
  }
}
```
appears to have proper digest hashes.  But can this be asserted/verified aside from the browser console error messages?

Note: at one point I reverted to duplicating and commenting out the importmap lines, but even the security blanket within the file of:
```
# pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
```
got removed.  I  literally had to spin up a new application to ensure I was getting things right (and fortunately allow me to stumble into another issue.. #160).

Possible expectations
• a non-manual recovery mechanism to default situation
• disallow dependencies to touch basic installations

**Comment by dhh** [comment]
Yeah, this is a constraint of importmap not being a full package manager. It doesn't know anything about dependencies. Feel free to add a note in the documentation about this, but I don't think we'll be able to solve the root issue.
