### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by pecha7x** [rails/importmap-rails#162]
Guys, I'm newbie in Import Map. And I want use that since this is a high recommended and so one of the main thing in Rails 7.
I've seen a lot of discussions about that and honestly everywhere say not to use it and back to Webpack/Yarn.

But In my opinion using Import Map should be one of the attractive features for involving new blood for RoR development at all. Using React.js with RoR as a main example. At least I see this as to get rid of the extra superstructure like using Node.js(and things that go with it) at RoR development workflow for myself.

But during learning this I ran into a problem when things out of the box don't work even at the stage of the simplest HelloWorld example for React app. 

`config/importmap.rb`- 
```
pin "application", preload: true
pin "react", to: "https://ga.jspm.io/npm:react@18.2.0/index.js"
pin "react-dom", to: "https://ga.jspm.io/npm:react-dom@18.2.0/index.js"
pin "react-dom/client", to: "https://ga.jspm.io/npm:react-dom@18.2.0/client.js"
pin "process", to: "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.27/nodelibs/browser/process-production.js"
pin "scheduler", to: "https://ga.jspm.io/npm:scheduler@0.23.0/index.js"
pin "htm/react", to: "https://ga.jspm.io/npm:htm@3.1.1/react/index.module.js"
pin "htm", to: "https://ga.jspm.io/npm:htm@3.1.1/dist/htm.module.js"
pin "react-router-dom", to: "https://ga.jspm.io/npm:react-router-dom@6.4.4/dist/index.js"
pin "@remix-run/router", to: "https://ga.jspm.io/npm:@remix-run/router@1.0.4/dist/router.js"
pin "react-router", to: "https://ga.jspm.io/npm:react-router@6.4.4/dist/index.js"
```

`javascript/application.js`- 
```
import ReactDOM from 'react-dom/client';
import { html } from 'htm/react';
import { BrowserRouter } from 'react-router-dom';

const el = document.getElementById('root');
const root = ReactDOM.createRoot(el);

root.render(
  html`
    <${BrowserRouter}>
      <h1>Hello There!</h1>
    <//>  
  `
);
```

This causes the error at Chrome browser - 
<img width="350" alt="Screenshot 2022-12-04 at 10 00 12" src="https://user-images.githubusercontent.com/3278961/205478653-7c8525eb-2650-4515-a5a1-dc40de96b0ee.png">

because `react-router` package has a direct dependence to Node.js - 
```
if (process.env.NODE_ENV !== "production") {
  DataStaticRouterContext.displayName = "DataStaticRouterContext";
}
```

So I see that due to disuse Node.js I fall with ImportMap even at this stage.
Found this solution through the discussion - https://github.com/rails/importmap-rails/issues/65 and there are a quick solution from @guybedford:
`Note as a quick fix you can also define it - <script>window.process = { env: {} }</script>`

Or smth like this - 
`<script>window.process = { env: { NODE_ENV: "#{Rails.env}" } }</script>`

For me it's look like a patch for porting npm packages which has dependence to Node and honestly this suits me.
And I would propose to include adding this row for default pin builder or smth like this.
But I don't see whole picture and don't know how it can affect in next when developing the application and adding new dependencies.

In any case I think it should be reflected at the README because this basic thing what requires to pay attention. otherwise this repels to use Import Mapping instead of Node and Yarn/Webpack.

**Comment by guybedford** [comment]
The other option for react-router-dom is to turn off the `"module"` condition when resolving in JSPM, since they check, since that then uses the CommonJS entry point, which JSPM support's `process.env` checks for fine. Eg see https://generator.jspm.io/#U2NgYGBkLM3ULc5IzclhKEpNTC7RLcovLUkt0k3Jz3Uw0zPRMwEAmpHlfSUA.

**Comment by dhh** [comment]
If you're building a full react app with the router and whatnot, it's probably too ambitious at this point to think import maps will be a smooth path. But great on you for trying!

The majority of apps that take the import map path, like hey.com, do so using Hotwire, which is also a Rails 7 default. That combination is much lighter than the heavy React path and has been well trodden at this point.

**Comment by ouaziz** [comment]
<script>
window.process = { env: { NODE_ENV: "production" } }
console.log(process.env);
console.log(process.env.HOME);
</script>
