### ISSUE TITLE
.\bin\importmap pin opens a file on Windows 10 and pins nothing

### ISSUE THREAD

**Issue by ShadowCrafter011** [rails/importmap-rails#170]
I am using Rails 7 and Windows 10. 
I ran rails importmap:install and that worked fine. I then wanted to import react and ran this command: `.\bin\importmap pin react react-dom`. But all this did was open the prompt where it asks what program you want to use to open a file. When I chose Editor it opened a file with this content:
```
#!/usr/bin/env ruby

require_relative "../config/application"
require "importmap/commands"
```
I also tried to run this with the ruby interpreter: `ruby .\bin\importmap pin react react-dom`. But no luck there either. All it did was throw this error: `No such file or directory @ rb_sysopen - config/importmap.rb (Errno::ENOENT)`

**Comment by SyedMSawaid** [comment]
Same issue.

**Comment by SyedMSawaid** [comment]
@ShadowCrafter011 I figured it out. You have to use git bash to run that commad.

What I actually think is that `.\bin\importmap` is a `.sh` and cmd or powershell can't run it so... yeah. Use `git bash`.

**Comment by ShadowCrafter011** [comment]
@SyedMSawaid Thanks for the suggestion. I went ahead and installed [Windows Subsystems for Linux](https://learn.microsoft.com/en-us/windows/wsl/install-manual) and got it to work that way.
