### ISSUE TITLE
Support for semver versioning

### ISSUE THREAD

**Issue by dkniffin** [rails/importmap-rails#173]
Is it possible to specify a minor version of a pinned package?

For example, I'm using [slim-select](https://slimselectjs.com/) in my project. It seems I need to add the following to my config file:

```
pin "slim-select", to: "https://ga.jspm.io/npm:slim-select@1.27.1/dist/slimselect.min.mjs"
```

But what happens if they release a 1.27.2? Or 1.28.0? Or 2.0?

`importmap outdated` seems to partially solve this. It would show me if there's a new version. But then I would need to determine on my own if I can upgrade to that version or not. For a patch version, I probably can. Maybe for a minor version. But a major version would require some more effort on my part, presumably.

The main question I guess is: how do I track which versions I can upgrade to and which ones I can't? Is that outside the scope of `importmap-rails`?

**Comment by jcoyne** [comment]
Agreed. It would be great to have the equivalent of `yarn upgrade` but I'd first need a way to provide a version specification.

**Comment by dhh** [comment]
I can appreciate wanting that, but turning importmap rails into a full package manager is out of scope. You can use outdated, and you'll have to manage the versions yourself.

**Comment by dkniffin** [comment]
I changed the title of this issue, because [semver doesn't currently support any kind of version range syntax, nor do they plan to](https://github.com/semver/semver/issues/205) and that's really what's needed here. iow, semver defines what `1.0.2` means, but as far as I can tell, it has no definition for things like `1.0.x`/`1.x.0`, or `~>2.0`, or `^2.0.8`, or `>= 3.0` or any of that kind of stuff.

**Comment by dkniffin** [comment]
Looping back here to mention that I created a gem to add this functionality: https://github.com/quimbee/importmap-package-manager It lets you separate your library imports into a separate `config/importmap_packages.yml` (which has allows defining version specs), then run `rake importmap_package_manager:update` to generate/update a `config/importmap-packages-lock.rb` file (which includes the sub-dependencies), which gets included in the importmap.
