### ISSUE TITLE
DOMContentLoaded fired twice

### ISSUE THREAD

**Issue by morgoth** [rails/importmap-rails#175]
I have basic setup with importmap-rails and propfshaft.

```js
// application.js
document.addEventListener('DOMContentLoaded', () => {
  console.log("I run")
})
```

```ruby
# config/importmap.rb
pin "application", preload: true
```

```
# layouts/application.html.erb
<%= javascript_importmap_tags("application") %>
```

I see that the code `console.log("I run")` is run twice.

Is it this a bug or some gotcha how the javascript modules work?

**Comment by dkniffin** [comment]
@morgoth Just a guess here, but I think it's supposed to be `javascript_importmap_tags` instead of `javascript_importmap_tags "application"`.

My understanding is that the `preload: true` automatically includes a script tag for `application`, and adding it to an argument includes it a second time.

**Comment by morgoth** [comment]
Passing "application" is just an explicit entry point, vide https://github.com/rails/importmap-rails/blob/main/app/helpers/importmap/importmap_tags_helper.rb#L3

The thing is that when I omit `document.addEventListener('DOMContentLoaded)'` it's called only once. :man_shrugging:

**Comment by morgoth** [comment]
I found what is causing it.
Loading shim. When I disable it by `javascript_importmap_tags("application", shim: false)` it works fine.

I'm using Firefox 109.0 so the importmaps are supported by default in this version.
Somehow the shim code does not recognize it properly

**Comment by morgoth** [comment]
This was fixed upstream https://github.com/guybedford/es-module-shims/pull/358
