### ISSUE TITLE
rails/importmap behind proxy not working

### ISSUE THREAD

**Issue by victorbucutea** [rails/importmap-rails#177]
While running behind a proxy with both `http_proxy` and `https_proxy` env variables setup I run into the following problem. 
It seems that packager.rb calls  Net::HTTP.post(...) which in turn ignores proxy settings. 

What to do in this case?

The following command `bin/importmap pin react@17.0.1` outputs :

  
     C:/...bin/ruby-3.1.2-1-x64/lib/ruby/3.1.0/net/http/response.rb:124:in 'error!': 407 "authenticationrequired" (Net::HTTPServerException)
        from C:/Users/x/bin/ruby-3.1.2-1-x64/lib/ruby/3.1.0/net/http/response.rb:133:in 'value'
        from C:/Users/xx/bin/ruby-3.1.2-1-x64/lib/ruby/3.1.0/net/http.rb:1020:in 'connect'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/3.1.0/net/http.rb:976:in 'do_start'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/3.1.0/net/http.rb:965:in 'start'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/3.1.0/net/http.rb:627:in 'start'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/3.1.0/net/http.rb:522:in 'post'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/importmap-rails-1.1.5/lib/importmap/packager.rb:67:in 'post_json'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/importmap-rails-1.1.5/lib/importmap/packager.rb:21:in 'import'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/importmap-rails-1.1.5/lib/importmap/commands.rb:17:in 'pin'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in 'run'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in 'invoke_command'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in 'dispatch'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in 'start'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/importmap-rails-1.1.5/lib/importmap/commands.rb:142:in '<top (required)>'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in 'require'
        from C:/Users/XXX/bin/ruby-3.1.2-1-x64/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in 'require'

**Comment by dhh** [comment]
Turn off the proxy or just download the file yourself.

**Comment by victorbucutea** [comment]
Now why did t I think of that... I could download 2k dependencies by hand.

**Comment by victorbucutea** [comment]
Or I could turn off the proxy which is the company proxy. You rock!

**Comment by dhh** [comment]
If you have 2k dependencies, then I don't think importmap is going to be the right fit for you. Do explore the esbuild option. Maybe that'll work better for you.
