### ISSUE TITLE
Javascript in head seems to be loading later than javascript in body

### ISSUE THREAD

**Issue by mlensment** [rails/importmap-rails#185]
I'm using Rails 7, Importmap, Turbo Drive and Haml for templates. I need to use Javascript in the view body, but it seems that on page refresh, the javascript in body loads sooner than javascript in head. That means that the libraries I'm trying to use are not loaded in time.

`application.js`
```
import "@hotwired/turbo-rails"
import 'jquery';
import 'select2'
```

`index.html.haml`
```
:javascript
  $('.select2').select2({
    placeholder: 'Choose...'
  });
```

Result:
`Uncaught ReferenceError: $ is not defined`

However, if I add delay, it works correctly:
```
:javascript
  setTimeout(function() {
    console.log('loaded')
    $('.select2').select2({
      placeholder: 'Choose...'
    });
  }, 1000);
```

**Comment by tayyab910629** [comment]
@mlensment where you able to fix this if yes please share, i have the same issue i have a cutom js file, i almost tried everything, and it is working fine on the page reload but after redirecting back from some action javascript stop working.
