### ISSUE TITLE
Impossible to make it work with PapaParse

### ISSUE THREAD

**Issue by troptropcontent** [rails/importmap-rails#190]
Hello :) 

I am pretty new with importmap and with javascript so my question might not be relevant but i am stuck :/

I would like to use this library in one of my view [PapaParse](https://github.com/mholt/PapaParse) to parse a csv and add rows into a table 

SI in my importmap.rb i have : 

`pin 'papaparse', to: 'https://unpkg.com/papaparse@5.4.1/papaparse.min.js'`

and in my stimulus controller : 

`import Papa from 'papaparse';`

but it does not work, in my browser i can see the following error : 

`The requested module 'papaparse' does not provide an export named 'default'`

Any idea of how to make this work ? :/

**Comment by guybedford** [comment]
Note that if you use the JSPM CDN option this should work - https://generator.jspm.io/#U2NhYGBkDM0rySzJSU1hKEgEwaLiVAdTPRM9QwAHAd/lHgA.

**Comment by troptropcontent** [comment]
thank you so much
