### ISSUE TITLE
Getting `Uncaught TypeError: The specifier "@hotwired/turbo-rails" was a bare specifier` after upgrading to the latest version of Firefox (115.0)

### ISSUE THREAD

**Issue by vlasar** [rails/importmap-rails#191]
Hello,

After upgrading to Firefox 115.0 (64-bit), on macOS 13.4, we are seeing the following error in the console and `Turbo` no longer working:

```
Uncaught TypeError: The specifier “@hotwired/turbo-rails” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.
```

<img width="1569" alt="SCR-20230705-mlzn" src="https://github.com/rails/importmap-rails/assets/220781/6015aac8-07ce-41ae-b8f6-bd0272ce5802">

---

Honestly, I'm not sure if this is a [rails/importmap-rails](https://github.com/rails/importmap-rails) or a [hotwired/turbo-rails](https://github.com/hotwired/turbo-rails) issue.

```Ruby
# config/importmap.rb
pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
```

```Javascript
// app/javascript/application.js
import { Turbo } from '@hotwired/turbo-rails'; // <- Error is raised here.

import 'controllers';

Turbo.session.drive = false;
```

<img width="1207" alt="SCR-20230705-mmfx" src="https://github.com/rails/importmap-rails/assets/220781/ea2c7a5e-09ff-4045-a5e1-ceadcbdacfd4">

**Comment by RifkyLTF** [comment]
I have the same issue. still looking for how to fix it

**Comment by guybedford** [comment]
Firefox having been resolving some bugs in their native import maps implementation. Perhaps some native behaviours changed with regards to load ordering in this release.  So long as the import map is loaded before the `<script type="module">` or `import()` that is attempting to use the import map, everything should behave correctly - so that if this is a bug, a fix that alters the HTML ordering should be possible. Note that es-module-shims will not be doing anything here, so this is entirely about native import maps support.

I'd suspect it's an importmap-rails debugging issue, based on careful analysis of the load ordering to ensure the import map fully loads before any module scripts.

**Comment by vlasar** [comment]
Thank you @guybedford.

We managed to resolve the issue by first rendering `javascript_importmap_tags` and then `javascript_include_tag "application"`.

So, instead of doing:

```ruby
<%= javascript_include_tag "application", :"data-turbo-track" => "reload" %>
<%= javascript_importmap_tags %>
```

we are now doing:

```ruby
<%= javascript_importmap_tags %>
<%= javascript_include_tag "application", :"data-turbo-track" => "reload" %>
```

I'm actually surprised we had it like that and that it worked.

**Comment by mkrajewski90** [comment]
> Thank you @guybedford.
> 
> We managed to resolve the issue by first rendering `javascript_importmap_tags` and then `javascript_include_tag "application"`.
> 
> So, instead of doing:
> 
> ```ruby
> <%= javascript_include_tag "application", :"data-turbo-track" => "reload" %>
> <%= javascript_importmap_tags %>
> ```
> 
> we are now doing:
> 
> ```ruby
> <%= javascript_importmap_tags %>
> <%= javascript_include_tag "application", :"data-turbo-track" => "reload" %>
> ```
> 
> I'm actually surprised we had it like that and that it worked.

I have only javascript_importmap_tags in my includes but it still doesn't work :(

**Comment by grncdr** [comment]
For others experiencing this issue, it seems like a Firefox bug has been opened here: https://bugzilla.mozilla.org/show_bug.cgi?id=1842792


[This comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1842792#c3) from Dennis Schubert seems particularly relevant:

> Apparently, this breaks only with the first non-module <script> tag in place. If you remove that, it works.

In my case, I had a plain `<script></script>` declaring some global variables before my `<%= javascript_importmap_tags %>`. Moving that below the importmap tags caused the issue to go away.

**Comment by yshmarov** [comment]
> For others experiencing this issue, it seems like a Firefox bug has been opened here: https://bugzilla.mozilla.org/show_bug.cgi?id=1842792
> 
> [This comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1842792#c3) from Dennis Schubert seems particularly relevant:
> 
> > Apparently, this breaks only with the first non-module <script> tag in place. If you remove that, it works.
> 
> In my case, I had a plain `<script></script>` declaring some global variables before `<%= javascript_importmap_tags %>`. Moving that below the importmap tags caused the issue to go away.

this worked for me. I moved the custom scripts and imports below `<%= javascript_importmap_tags %>`

**Comment by lxxxvi** [comment]
I had the same error message, but I didn't have any custom scripts or alike above `<%= javascript_importmap_tags %>`, so all suggestions didn't work for me.

However, in my case the `turbo-rails` gem was missing in the bundle 🤦, so adding

```ruby
gem "turbo-rails"
```

to the `Gemfile` solved my issue.
