### ISSUE TITLE
Firefox fails to load module pinned to HTTP path when using CSP-nonce 

### ISSUE THREAD

**Issue by KeithP** [rails/importmap-rails#193]
This is happening with a new Rails 7.0.6 app with bootstrap & popperjs pinned to the jspm HTTP path and a simple "hello" stimulus controller to log its presence. The app is secured with a CSP with a nonce applied to 'script-src' & 'style-src' directives.

When you run the app locally in the production environment, the homepage works as expected in Chrome/Edge but in Firefox the console contains warnings and the hello stimulus controller fails to run. 

The problem goes away when you comment out the whole CSP, but we don't want that. 
The problem doesn't exist in the Rails development environment, unless you add config.assets.prefix = "/dev-assets" to config/envronments/development.rb. 

![image](https://github.com/rails/importmap-rails/assets/265490/46412d96-91f9-423b-80a7-40c5b41a52c0)

**Comment by dhh** [comment]
Version 2 will now download and vendor all pins, so this should no longer be an issue.

**Comment by KeithP** [comment]
Looks good, version 2.0.1 appears to have resolved this.

Cant be completely conclusive as I am no longer able to reproduce the original error using version 1.2.3.
Thank you tho.
