### ISSUE TITLE
Add an option to include the shim script as `defer` instead of `async`

### ISSUE THREAD

**Issue by JanPokorny** [rails/importmap-rails#195]
Although the `es-modules-shims` script recommends including it as `async` in their README, this can lead to bugs as on browsers that support executing `type="module"` scripts out of the box, the `async` script might not execute before the module, leading to the `importShim` function not being available: https://github.com/guybedford/es-module-shims/issues/385

This can be mitigated by changing `async` to `defer` when including the shim -- deferred scripts go into the same queue as modules, thus it guarantees that the shim will be executed first, before the module.

**Comment by JanPokorny** [comment]
As explained in the linked issue, it actually only makes sense to do this if the script needs to rely on `importShim` (which is only when there are no static imports to trigger the polyfilling mechanism). In the general case `async` is better than `defer`, but still having an option to choose between async/defer would be nice

**Comment by dhh** [comment]
We're dropping the shim in version 2, so this is no longer relevant.
