### ISSUE TITLE
The asset "actioncable.esm.js" is not present in the asset pipeline.

### ISSUE THREAD

**Issue by leehericks** [rails/importmap-rails#2]
Thank you so much for this gem and really shaping up Hotwire!

I'm upgrading an asset pipeline only Hotwire app on Rails 6.1.4.

I assume these will be available automatically in Rails 7,
but how should we go about getting the three javascript files added to assets.rb by the installer?

**Comment by leehericks** [comment]
Clearly and understandably there is currently a name mismatch as looking in the rails source code yields `action_cable.js`, but even correcting the name throws up an error about the assets not being precompiled, and running `rails assets:precompile` also doesn’t link these files.

**Comment by dhh** [comment]
Yeah, this relies on a ESM compilation that's only present in rails/main at the moment. Will look at something to make it compatible with released rails.

**Comment by dhh** [comment]
I'd say actually that the easiest way to proceed if you want to play with this already, though, is to get on rails/main. Expect a fair amount of churn until all this settles!

**Comment by leehericks** [comment]
I may have jumped the gun as this is a semi-production app with organization-wide use from October but I have struggled incredibly trying to get ActiveStorage direct upload working via the rails guide instructions, possibly because I'm missing UJS? But the activestorage.js looks independent and feature complete. Was hoping this new JavaScript architecture might fix my problems with that regard.

**Comment by dhh** [comment]
There are plenty of production apps running off rails/main, but yeah, probably wouldn't use that approach as a way to route around a bug or misconfiguration with AS 😄. Especially since there's likely to be considerable churn to how the importmap approach works before it's ready for shipping.

**Comment by dhh** [comment]
For now, we skip missing pins instead of dying.
