### ISSUE TITLE
Unable to complete installation on existing rails 6 app 

### ISSUE THREAD

**Issue by muriloime** [rails/importmap-rails#20]
The command `./bin/rails importmap:install` is always giving me an error 

`NoMethodError: undefined method `paths' for #<Importmap::Map:0x000055db94454028 @files={}, @directories={}>` 

on the rails initialization process. I've tried many versions of the gems to no avail. Maybe there is something missing on the documentation? 

My rails version is 6.1.3.2

Many thanks

**Comment by dhh** [comment]
You need the latest version of turbo-rails, stimulus-rails, and importmap-rails all together. Previous versions used different APIs.
