### ISSUE TITLE
Different modules for, say, admin namespace

### ISSUE THREAD

**Issue by varyform** [rails/importmap-rails#23]
Hi, 
I tried `javascript_importmap_tags "admin"` in a separate layout.
But in both cases all the modules were included (`application` one includes admin as well and vice versa).

Is it possible? I don't need all the stuff for, say, public part (except `turbo`).

Thanks!

**Comment by dhh** [comment]
You'll need to manually setup a separate importmap object: https://github.com/rails/importmap-rails/blob/main/lib/importmap/map.rb

Then pass it by hand to the helper: https://github.com/rails/importmap-rails/blob/main/app/helpers/importmap/importmap_tags_helper.rb#L14

**Comment by maxhoffmann** [comment]
@dhh I’d really appreciate if to have more documentation about this in the readme. Especially about how to set up a separate importmap object manually. I tried `javascript_importmap_tags "something"`, which changed `import application;` to `import something;`, but it’s not listed in the import map like `application.js` and produces an error.

More documentation about how to configure Rails to have multiple JS entry points would be amazing. 🙏

**Comment by varyform** [comment]
@risinglf https://gist.github.com/varyform/92be68c3ea2d94d31de3c3359284c0e5

**Comment by henrikbjorn** [comment]
@dhh Can this be reopened, it would be a great feature to support out the box. Either in the default `importmap` with something like `pin "asset", to: "my url", under: "activeadmin"` where `under:` defaults to `"application"`
