### ISSUE TITLE
Break in iOS 16.2 when upgrading from 1.2.3 to 2.0.1

### ISSUE THREAD

**Issue by code-bunny** [rails/importmap-rails#232]
I wasn't too vigilant and bundle updated my rails application which pulled in the 2.0.1 importmaps. This seemed to be perfectly fine until we had iPhone users still running 16.2 reporting that the website was "frozen". It turns out that the error was due to:

TypeError: Module specifier, 'application' does not start with "/", "./", or "../". Referenced from http://localhost:3001/ 

Replace the from with the production websites domain or indeed any domain with this issue. Reverting to 1.2.3 fixes the issue or upgrading iOS to any of the 17.x releases also fixes the issue.

**Comment by code-bunny** [comment]
Of note in 1.2.3 there is a green message reporting that ```^^ Module TypeError above is polyfilled and can be ignored ^^```

**Comment by morgoth** [comment]
@code-bunny I belive it's because removing the shim from version 2.0, ie https://github.com/rails/importmap-rails/pull/216

In comments you can read how to bring it back to version 2.0 of this gem

**Comment by code-bunny** [comment]
@morgoth thanks for the link to the reference! I'll keep myself on the v1 for a while and "encourage" the users to upgrade their iOS versions or push them over to the native app... once I build it.

**Comment by morgoth** [comment]
can you close the issue then?
