### ISSUE TITLE
turbo:load event not fired anymore in test environment after upgrade from 1.2.3 to 2.0.1

### ISSUE THREAD

**Issue by cryptogopher** [rails/importmap-rails#233]
I have an app that hides page until `turbo:load` event. This works properly with importmap-rails 1.2.3:
```
$ [master] cat application.js 
// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"

function showPage(event) {
  document.documentElement.style.visibility="visible";
}
document.addEventListener('turbo:load', showPage);
```

After upgrade to 2.0.1 it still works in development environment, but system tests no longer pass as the page is never made visible (i.e. the `turbo:load` event seems not to be fired). Any suggestion how to fix that?

**Comment by andrewyoo** [comment]
What driver are you using for your system tests? importmaps v2 removes the compatibility shim for older browsers as noted in their [changelog](https://github.com/rails/importmap-rails/releases/tag/v2.0.0).

I just ran into this as it broke my app for older versions of ios using safari < 16.4.

**Comment by cryptogopher** [comment]
@andrewyoo Thank you for reply. I'm using geckodriver/Firefox 102.12.0 - that could explain the problem I'm facing.

**Comment by andrewyoo** [comment]
I downgraded this gem as well to keep supporting my users. It looks like you need firefox >= 108.
https://caniuse.com/import-maps

<img width="505" alt="Screenshot 2024-01-17 at 4 07 45 PM" src="https://github.com/rails/importmap-rails/assets/270819/c6d80085-4381-480c-ada2-8fb3991a2137">
