### ISSUE TITLE
Importmap update removes pins via http

### ISSUE THREAD

**Issue by DalenW** [rails/importmap-rails#242]
If I have this pinned: `pin "@popperjs/core", to: "https://ga.jspm.io/npm:@popperjs/core@2.11.7/lib/index.js"` and then run `./bin/importmap update`, it will remove the url and instead pin it from disk by changing the line to `pin "@popperjs/core", to: "@popperjs--core.js" # @2.11.8`. Issue this that this completly breaks popperjs functionality. It's required for bootsrap. 

Updating the pin's link to the latest version does prevent the update, but it shouldn't break the pin altogether when running update. You can probably close this right away if that's by design.

**Comment by Caleb-T-Owens** [comment]
This is a known issue and should be resolved by https://github.com/rails/importmap-rails/pull/235
