### ISSUE TITLE
importmap pin/update removes preload: false

### ISSUE THREAD

**Issue by mhenrixon** [rails/importmap-rails#243]
When I run `importmap pin @turbo-boost/commands` it changes the `importmaps.rb` line from:

```ruby
pin "@turbo-boost/commands", to: "@turbo-boost--commands.js", preload: false # @0.0.16
```

To:

```ruby
pin "@turbo-boost/commands", to: "@turbo-boost--commands.js" # @0.0.16
```

I believe that it should keep any existing `preload: false`

**Comment by dhh** [comment]
There's no such guarantee of persistence when using the pin command. It's a fine line here, but we can't and won't turn this into a full-blown package manager, so going to call this out of scope at the moment.
