### ISSUE TITLE
How to add jquery in importmaps rails 7

### ISSUE THREAD

**Issue by tayyab910629** [rails/importmap-rails#250]
I hope you guys doing well
i need to add jquery to my project but so far now luck, i can add jquery this like this by commenting "<%= javascript_importmap_tags %>" from layout but this causes other issues, so i am trying now from import metthod way, i tried many CDN, etc link like this but no luck so far, this is my importmap file looks like 

# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "jquery", to: "https://cdn.skypack.dev/pin/jquery@v3.7.1-7rUWvYxyB0VFidIbWTia/mode=imports,min/optimized/jquery.js"
pin "flash", to: "flash.js", preload: true

and in the application.js i have this 

import "@hotwired/turbo-rails"
import "controllers"
import $ from "jquery"
 anyone please help me with the correct way of adding Jquery in rails

**Comment by tayyab910629** [comment]
Update : i tires this way and its working but not sure if this is the properway of doing it, 

this is my importmap. file content.
# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"


pin "jquery", to: "jquery_module.js" ,preload: true
pin "script", to: "script.js"
pin "tabby", to: "tabby_module_wrapper.js"

pin "jquery_mask", to: "jquery.mask.min.js"
pin "owl_carousel", to: "owl.carousel.min.js"
pin "flash", to: "flash.js"

I created jquery_module.js file and added this

 // app/javascript/jquery_wrapper.js

import './jquery-3.6.0.min.js';

window.$ = window.jQuery = jQuery;

export default jQuery;

**Comment by rafaelfranca** [comment]
Please use https://discuss.rubyonrails.org/ for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
