### ISSUE TITLE
@uppy/dashboard and @uppy/remote-source fail to install.

### ISSUE THREAD

**Issue by mattstone** [rails/importmap-rails#255]
Hello,

Initially reported on jspm, Guy has said this may be an importmap-rails issue: https://github.com/jspm/project/issues/338.

My environment

OSX Sonoma
Ruby 3.3.3
Rails 7.1.3.4

Steps to reproduce..

bin/importmap pin @uppy/core is succesfull.

bin/importmap pin @uppy/dashboard fails when attempting to install lodash

Using bin/importmap pin @uppy/dashboard --from jspm and 
Using bin/importmap pin @uppy/dashboard --from jspm.io generate the same response 

Pinning "@uppy/dashboard" to vendor/javascript/@uppy/dashboard.js via download from https://ga.jspm.io/npm:@uppy/dashboard@3.9.1/lib/index.js
Pinning "@transloadit/prettier-bytes" to vendor/javascript/@transloadit/prettier-bytes.js via download from https://ga.jspm.io/npm:@transloadit/prettier-bytes@0.3.4/dist/prettierBytes.js
Pinning "@uppy/core" to vendor/javascript/@uppy/core.js via download from https://ga.jspm.io/npm:@uppy/core@3.13.0/lib/index.js
Pinning "@uppy/informer" to vendor/javascript/@uppy/informer.js via download from https://ga.jspm.io/npm:@uppy/informer@3.1.0/lib/index.js
Pinning "@uppy/provider-views" to vendor/javascript/@uppy/provider-views.js via download from https://ga.jspm.io/npm:@uppy/provider-views@3.13.0/lib/index.js
Pinning "@uppy/status-bar" to vendor/javascript/@uppy/status-bar.js via download from https://ga.jspm.io/npm:@uppy/status-bar@3.3.3/lib/index.js
Pinning "@uppy/store-default" to vendor/javascript/@uppy/store-default.js via download from https://ga.jspm.io/npm:@uppy/store-default@3.2.2/lib/index.js
Pinning "@uppy/thumbnail-generator" to vendor/javascript/@uppy/thumbnail-generator.js via download from https://ga.jspm.io/npm:@uppy/thumbnail-generator@3.1.0/lib/index.js
Pinning "@uppy/utils/lib/FOCUSABLE_ELEMENTS" to vendor/javascript/@uppy/utils/lib/FOCUSABLE_ELEMENTS.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/FOCUSABLE_ELEMENTS.js
Pinning "@uppy/utils/lib/Translator" to vendor/javascript/@uppy/utils/lib/Translator.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/Translator.js
Pinning "@uppy/utils/lib/VirtualList" to vendor/javascript/@uppy/utils/lib/VirtualList.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/VirtualList.js
Pinning "@uppy/utils/lib/dataURItoBlob" to vendor/javascript/@uppy/utils/lib/dataURItoBlob.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/dataURItoBlob.js
Pinning "@uppy/utils/lib/emaFilter" to vendor/javascript/@uppy/utils/lib/emaFilter.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/emaFilter.js
Pinning "@uppy/utils/lib/findAllDOMElements" to vendor/javascript/@uppy/utils/lib/findAllDOMElements.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/findAllDOMElements.js
Pinning "@uppy/utils/lib/findDOMElement" to vendor/javascript/@uppy/utils/lib/findDOMElement.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/findDOMElement.js
Pinning "@uppy/utils/lib/generateFileID" to vendor/javascript/@uppy/utils/lib/generateFileID.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/generateFileID.js
Pinning "@uppy/utils/lib/getDroppedFiles" to vendor/javascript/@uppy/utils/lib/getDroppedFiles.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/getDroppedFiles/index.js
Pinning "@uppy/utils/lib/getFileNameAndExtension" to vendor/javascript/@uppy/utils/lib/getFileNameAndExtension.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/getFileNameAndExtension.js
Pinning "@uppy/utils/lib/getFileType" to vendor/javascript/@uppy/utils/lib/getFileType.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/getFileType.js
Pinning "@uppy/utils/lib/getTextDirection" to vendor/javascript/@uppy/utils/lib/getTextDirection.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/getTextDirection.js
Pinning "@uppy/utils/lib/getTimeStamp" to vendor/javascript/@uppy/utils/lib/getTimeStamp.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/getTimeStamp.js
Pinning "@uppy/utils/lib/isDragDropSupported" to vendor/javascript/@uppy/utils/lib/isDragDropSupported.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/isDragDropSupported.js
Pinning "@uppy/utils/lib/isObjectURL" to vendor/javascript/@uppy/utils/lib/isObjectURL.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/isObjectURL.js
Pinning "@uppy/utils/lib/isPreviewSupported" to vendor/javascript/@uppy/utils/lib/isPreviewSupported.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/isPreviewSupported.js
Pinning "@uppy/utils/lib/prettyETA" to vendor/javascript/@uppy/utils/lib/prettyETA.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/prettyETA.js
Pinning "@uppy/utils/lib/remoteFileObjToLocal" to vendor/javascript/@uppy/utils/lib/remoteFileObjToLocal.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/remoteFileObjToLocal.js
Pinning "@uppy/utils/lib/toArray" to vendor/javascript/@uppy/utils/lib/toArray.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/toArray.js
Pinning "@uppy/utils/lib/truncateString" to vendor/javascript/@uppy/utils/lib/truncateString.js via download from https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/truncateString.js
Pinning "classnames" to vendor/javascript/classnames.js via download from https://ga.jspm.io/npm:classnames@2.5.1/index.js
Pinning "eventemitter3" to vendor/javascript/eventemitter3.js via download from https://ga.jspm.io/npm:eventemitter3@5.0.1/index.mjs
Pinning "exifr/dist/mini.esm.mjs" to vendor/javascript/exifr/dist/mini.esm.mjs.js via download from https://ga.jspm.io/npm:exifr@7.1.3/dist/mini.esm.mjs
Pinning "is-shallow-equal" to vendor/javascript/is-shallow-equal.js via download from https://ga.jspm.io/npm:is-shallow-equal@1.0.1/index.js
**Pinning "lodash/" to vendor/javascript/lodash/.js via download from https://ga.jspm.io/npm:lodash@4.17.21/**
**/Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:80:in `handle_failure_response': Unexpected response code (404) (Importmap::Packager::HTTPError)**
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:118:in `download_package_file'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:57:in `download'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:19:in `block in pin'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:17:in `each'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:17:in `pin'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:141:in `<main>'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
	from bin/importmap:4:in `<main>'

/Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:69:in rescue in post_json': Unexpected transport error (Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>) (Importmap::Packager::HTTPError) from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:66:in post_json'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:21:in import' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:16:in pin'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in run' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in invoke_command'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in dispatch' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/base.rb:584:in start'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:141:in <main>' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in require'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in block (2 levels) in replace_require' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in require'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in require' from bin/importmap:4:in 

'
/Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/net/protocol.rb:229:in rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout) from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/net/protocol.rb:199:in readuntil'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/net/protocol.rb:209:in readline' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http/response.rb:158:in read_status_line'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http/response.rb:147:in read_new' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:2342:in block in transport_request'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:2333:in catch' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:2333:in transport_request'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:2306:in request' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-mini-profiler-3.3.1/lib/patches/net_patches.rb:19:in block in request_with_mini_profiler'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-mini-profiler-3.3.1/lib/mini_profiler/profiling_methods.rb:50:in step' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-mini-profiler-3.3.1/lib/patches/net_patches.rb:18:in request_with_mini_profiler'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:2320:in send_entity' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:1973:in post'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:858:in block in post' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:1570:in start'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:1029:in start' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:856:in post'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:67:in post_json' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:21:in import'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:16:in pin' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in run'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in invoke_command' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in dispatch'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/base.rb:584:in start' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:141:in '
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in require' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in block (2 levels) in replace_require'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in require' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in require'
from bin/importmap:4:in `'
bin/importmap pin @uppy/remote-sources --from jspm also fails with this.

/Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:69:in rescue in post_json': Unexpected transport error (Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>) (Importmap::Packager::HTTPError) from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:66:in post_json'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:21:in import' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:16:in pin'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in run' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in invoke_command'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in dispatch' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/base.rb:584:in start'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:141:in <main>' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in require'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in block (2 levels) in replace_require' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in require'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in require' from bin/importmap:4:in 

'
/Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/net/protocol.rb:229:in rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout) from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/net/protocol.rb:199:in readuntil'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/net/protocol.rb:209:in readline' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http/response.rb:158:in read_status_line'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http/response.rb:147:in read_new' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:2342:in block in transport_request'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:2333:in catch' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:2333:in transport_request'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:2306:in request' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-mini-profiler-3.3.1/lib/patches/net_patches.rb:19:in block in request_with_mini_profiler'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-mini-profiler-3.3.1/lib/mini_profiler/profiling_methods.rb:50:in step' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-mini-profiler-3.3.1/lib/patches/net_patches.rb:18:in request_with_mini_profiler'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:2320:in send_entity' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:1973:in post'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:858:in block in post' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:1570:in start'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:1029:in start' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:856:in post'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:67:in post_json' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/packager.rb:21:in import'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:16:in pin' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in run'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in invoke_command' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in dispatch'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/base.rb:584:in start' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:141:in '
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in require' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in block (2 levels) in replace_require'
from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in require' from /Users/mattstone/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in require'
from bin/importmap:4:in `'

**Comment by dhh** [comment]
With such a dependency waterfall, you may well be better off pursuing jsbundling-rails. Important maps are great for contained distributions, but not this kind of stuff.
