### ISSUE TITLE
Upgrade from version 1.2.3 to 2.0.1 causes "An import map is added after module script load was triggered."

### ISSUE THREAD

**Issue by vikas-wadhwa** [rails/importmap-rails#258]
Our app is testing an upgrade to importmap-rails 2.0.1, coming from 1.2.3.

With no other changes, however, we are now getting this error: 

```
An import map is added after module script load was triggered.
Uncaught TypeError: Failed to resolve module specifier "application". Relative references must start with either "/", "./", or "../".
```

I suspect this is because preloading is now the default but we'd have to go through a lot of files to determine if this is the case. Are there any other reasons this would happen that you can think of?

Comparing the raw view-source and final DOM shows no changes except for csrf tags and such. Any ideas?

**Comment by dhh** [comment]
Sounds right that it might be a preload change. Anyway, without further updates since July, I assume you figured it out.
