### ISSUE TITLE
Pinning `highlight.js` does not work (Probably not an issue with importmap-rails)

### ISSUE THREAD

**Issue by tagliala** [rails/importmap-rails#270]
Hello,

I was trying to use `importmap-rails` to vendor [`highlight.js`](https://www.npmjs.com/package/highlight.js)

As a non-javascript developer I'm struggling into understanding whether this is an issue with `importmap-rails` (probably it isn't) or in highlight.js, which is not importmap friendly when it comes to vendoring javascript files (can't use the cdn)

I only need to highlight json files for testing purposes, so I wanted to pin `highlight.js/lib/core` and `highlight.js/lib/languages/json`

The following happens when trying to pin `core`:

```
$ bin/importmap pin highlight.js/lib/core
Pinning "highlight.js/lib/core" to vendor/javascript/highlight.js/lib/core.js via download from https://ga.jspm.io/npm:highlight.js@11.10.0/es/core.js

$ cat vendor/javascript/highlight.js--lib--core.js 
// highlight.js/lib/core@11.10.0 downloaded from https://ga.jspm.io/npm:highlight.js@11.10.0/es/core.js

import o from"../lib/core.js";export{o as HighlightJS,o as default};
```

As you can see there is a relative import to `../lib/core.js`, and that results in a 404 error in the browser console.

Pinning `highlight.js/lib/languages/json` works instead, because the code is actually there

By inspecting the package source at https://www.npmjs.com/package/highlight.js?activeTab=code, I can see that `package.json` has some exports related to core: 

```
    "./lib/core": {
      "require": "./lib/core.js",
      "import": "./es/core.js"
    },
```

Should I report this to highlight.js?

Thanks for any help you can provide

**Comment by joshgoebel** [comment]
The ES6 modules provided with the default npm package are "dual use" (I forget the term) and really intended only for use with Node.js. They were built using the recommended strategy at the time so that you couldn't accidentally load the CJS and ES6 modules side by side and have different objects. (since HighlightJS has traditionally been a singleton object)

If you want module ready to use in the browser please use our CDN assets, which are full ES6.

https://www.npmjs.com/package/@highlightjs/cdn-assets

These are "pure" ES6 and should be good to go with Rails importmap, whatever, as far as I know.

**Comment by tagliala** [comment]
Thanks for your answer

> If you want module ready to use in the browser please use our CDN assets, which are full ES6.

As far as I understand, I should replace

```sh
bin/importmap pin highlight.js
```

with

```sh
bin/importmap pin @highlightjs/cdn-assets
```

but the latter does not work.

After a few tries, I ended up with

```
bin/importmap pin @highlightjs/cdn-assets/es/core.min.js --from=jsdelivr
bin/importmap pin @highlightjs/cdn-assets/es/languages/json.min.js --from=jsdelivr
```

And it's working, thanks

**Comment by joshgoebel** [comment]
Yeah, there are ALSO CJS assets in that package, but the ES assets live inside the `es` folder.  That's likely why the straight import doesn't work.

**Comment by tagliala** [comment]
> I wonder what this would do:
> 
> ```
> bin/importmap pin @highlightjs/cdn-assets/es
> ```

they don't work:
```
$ bin/importmap pin @highlightjs/cdn-assets/es
Couldn't find any packages in ["@highlightjs/cdn-assets/es"] on jspm

$ bin/importmap pin @highlightjs/cdn-assets/es --from=jsdelivr
Couldn't find any packages in ["@highlightjs/cdn-assets/es"] on jsdelivr
```

**Comment by joshgoebel** [comment]
Ah it must be hard coded to work with npm names, maybe? Annoying.

**Comment by tagliala** [comment]
As an update, a drawback with this approach is that outdated packages are not being detected

Example:

```
$ bin/importmap pin @highlightjs/cdn-assets@11.10.0/es/core.min.js --from=jsdelivr
Pinning "@highlightjs/cdn-assets/es/core.min.js" to vendor/javascript/@highlightjs/cdn-assets/es/core.min.js.js via download from https://cdn.jsdelivr.net/npm/@highlightjs/cdn-assets@11.10.0/es/core.min.js

$ bin/importmap outdated
No outdated packages found
```

---

```
$ bin/importmap pin highlight.js@11.10.0 --from=jsdelivr
Pinning "highlight.js" to vendor/javascript/highlight.js.js via download from https://cdn.jsdelivr.net/npm/highlight.js@11.10.0/es/index.js

$ bin/importmap outdated
| Package      | Current | Latest  |
|--------------|---------|---------|
| highlight.js | 11.10.0 | 11.11.1 |
  1 outdated package found
```

The "problem" is here:

https://github.com/rails/importmap-rails/blob/d91d5e134d3f27e2332a8cb2ac015ea03d130621/lib/importmap/npm.rb#L51-L52
