### ISSUE TITLE
Should importmap include /vendor/assets by default?

### ISSUE THREAD

**Issue by leehericks** [rails/importmap-rails#3]
With the initial release of Hotwire, I put ESM versions of javascript libraries like SortableJS into `/app/assets/javascripts/libraries` which was generated by the stimulus gem (if I remember correctly).

With import maps, it seems like I need to update all import statements to be relative to the javascripts folder, such that in my sortable controller I need `import Sortable from "libraries/sortable"`.

But more importantly, this `libraries` folder is no longer generated in a new install, which prompted me to go back to the Asset Pipeline guide and review the meaning of the `vendor` folder.

Should this gem automatically be mapping `/vendor/assets/javascripts` or should I add those assets manually to `/config/initializers/assets.rb`?

**Comment by dhh** [comment]
Yeah, I think vendor is a good spot for the libraries. Going to look into something like skygrab that could fetch the library you're looking for from a place ala skycap and save it there. Will look at doing that together with a new default.

While you're running on the add, I think manually adding the assets is the way to go 👍

**Comment by leehericks** [comment]
@dhh 
Adding `paths.asset "sortable", path: "vendor/assets/javascripts/sortable@1.13.0.esm.js"` to assets.rb

still results in:

The asset "vendor/assets/javascripts/sortable@1.13.0.esm.js" is not present in the asset pipeline.

Is there another piece of the puzzle I'm missing?

**Comment by dhh** [comment]
Yes, you need to link vendor/assets/javascripts in your config/manifest.js, like: `//= link_tree ../../../vendor/assets/javascripts`, then you add the assets via assets.rb.

**Comment by leehericks** [comment]
Makes perfect sense. Sorry for the miss and thank you!

**Comment by dhh** [comment]
It's a good reminder though that we need to iron all this out. Shouldn't have to manually configure any of this.
