### ISSUE TITLE
v 0.5.3 - es-module-shim script still blocked by Content Security Policy 

### ISSUE THREAD

**Issue by ccasabona** [rails/importmap-rails#32]
Thanks for adding the content security policy nonce awareness to the importmap_tags_helpers.  Adding es-module-shim, however, is generating this script in the header:

`<script type="esms-options">{"nonce":"PvInLekGVYkMB8sUJCUZ8fg/1q+UWuNyJlI="}</script>`

This fails csp with:

`Refused to load the script 'http://localhost:3000/assets/es-module-shims-a1fc5fe40f250a03bc2e7a9b90c68adb1ee2c1b40d1a87f2554941d0c5232a11.js' because it violates the following Content Security Policy directive: "script-src 'self' https: 'strict-dynamic'...`

Importmaps-rails 0.5.3
Rails 7.0.0.alpha2
Ruby 3.0.2

**Comment by dhh** [comment]
Fixed via https://github.com/rails/importmap-rails/commit/fd3875bebde3ef0e410af4bd70c107ae862157b0 which is included in 0.6.0. Thanks!

**Comment by ccasabona** [comment]
Thank-you for fixing so quickly.
