### ISSUE TITLE
Intentions for integrating with Propshaft?

### ISSUE THREAD

**Issue by rmacklin** [rails/importmap-rails#42]
I know development on this stuff is still very much in progress, but is it correct to assume that we'll want this gem to work with Propshaft (i.e. in apps that use an alternative asset pipeline to Sprockets)? From what I've seen so far, it doesn't seem like the gem needs any of the more complex Sprockets-specific stuff.

But I noticed the gem currently has a direct reference to a Sprockets constant here:
https://github.com/rails/importmap-rails/blob/a2e563218399f31bf8a34d8423feb6d2a5846660/lib/importmap/map.rb#L94

Would we want to generalize it such that we only reference that constant when Sprockets has been loaded (after checking `if defined?(Sprockets::Rails)` or something similar)?

**Comment by dhh** [comment]
Yes, let's definitely guard against this. Propshaft should indeed be made compatible here.

**Comment by rmacklin** [comment]
Sounds good, I'll work on a PR. And likely one as well in https://github.com/rails/propshaft.
