### ISSUE TITLE
Uncaught TypeError: Error resolving module specifier “application” on Rails 7 in Firefox

### ISSUE THREAD

**Issue by murdoch** [rails/importmap-rails#46]
I see the following 2 console warnings in FireFox after creating a rails 7 app.

---

**The first warning:**

```
Uncaught TypeError: Error resolving module specifier “application”. Relative module specifiers must start with “./”, “../” or “/”.
```

The warning points to the following line of code:

```
<script type="module">import "application"</script>
```

Any javascript I place in application.js appears to work as expected. Turbolinks and Trix work correctly too.

---

**The second warning:** 

```
asm.js type error: Disabled because no suitable wasm compiler is available
```

The above warning points to the es shim js file.

---

These warnings only appear in Firefox.

![Screen Shot 2021-10-02 at 2 15 53 AM](https://user-images.githubusercontent.com/56636/135699360-48d79207-714c-4919-bfc8-a1b4bf44202f.png)

---

**To reproduce:**

- rails new internetwebsite
- rails g scaffold posts title
- rails db:migrate
- rails s
- open localhost:3000/posts

---

**Additional info:**

- Using Ruby 3.0.2
- Not using yarn/node/esbuild etc
- Happens with both the alpha gems
- Happens when pulling rails directly from github 
- No warnings in Chrome or Safari
- MacOs Big Sur 11.6
- FireFox 92.0.1

**Comment by dhh** [comment]
First warning is expected and natural for this setup. See the readme for the documentation.

The second one is new to me. @guybedford ?

**Comment by guybedford** [comment]
The `"asm.js type error: Disabled because no suitable wasm compiler is available"` error is because when opening the developer tools in Firefox, running the Debugger disables asm.js optimizations. If you navigate to about:config and disable the debugger, then reopen the page, it will go away and you should see something like "asm.js compiled successfully". Important to bear in mind when doing benchmarks that opening the console always changes the result (although this is very true in Chrome as well!). The asm.js optimizations are fully applied in Firefox normally.

**Comment by murdoch** [comment]
Thanks @dhh and @guybedford. I confirm I see `Successfully compiled asm.js code` after disabling the debugger.

![Screen Shot 2021-10-03 at 1 41 24 PM](https://user-images.githubusercontent.com/56636/135754180-dcec9ccf-1a2c-4734-9802-3d3a70ea7272.png)

**Comment by dhh** [comment]
Worth adding a note to the docs about this asm.js compile / Firefox debugger. Just so there's a mention of it in case someone else ponders it.

**Comment by sedubois** [comment]
> First warning is expected and natural for this setup. See the readme for the documentation.

How to indicate these errors are expected? We would like to avoid getting these reported to Sentry as they eat into our error quota. We can set [ignore rules](https://docs.sentry.io/clients/javascript/config/) like below, however it is not comprehensive as the message depends on both the browser and the user language. It also adds extra code to the HTML response.

```js
Sentry.init({
  // ...
  ignoreErrors: [
    "Uncaught TypeError: Error resolving module specifier “application”. Relative module specifiers must start with “./”, “../” or “/”.",
    "Failed to resolve module specifier \"application\". Relative references must start with either \"/\", \"./\", or \"../\".",
    "Erreur lors de la résolution du spécificateur de module « application ». Les spécificateurs de module relatifs doivent commencer par « ./ », « ../ » ou « / ».",
    "Fehler beim Auflösen des Modulspezifierers \"application\". Relative Modulspezifierer müssen mit \"./\", \"../\" oder \"/\" beginnen."
    // ... ?
  ],
});
```
