### ISSUE TITLE
rails importmap:install creates app/javascript/application.js

### ISSUE THREAD

**Issue by shafy** [rails/importmap-rails#7]
Running `rails importmap:install` creates the entrypoint file in `app/javascript/application.js` instead of `app/assets/javascripts/application.js`.

If I delete it and add `app/assets/javascripts/application.js` manually and install Stimulus, it can't find my controllers:

```
Failed to autoload controller: chart Error: Unable to resolve specifier 'chart_controller' from <path>
```

Before switching to `importmap-rails` I had `webpacker` installed - can it have something to do with that? Although I uninstalled `webpacker` and deleted all files before installing `importmap-rails`.

**Comment by leehericks** [comment]
This gem is in active development. Expect it to change daily. If you check the commits, DHH just moved the directory to promote that JavaScript is more than an asset.

**Comment by shafy** [comment]
I see, thanks for the pointer. Do you know if that means that Stimulus controllers should also be installed in `app/javascript/controllers` going forward, like they are when you use Webpacker?

**Comment by leehericks** [comment]
turbo-rails and stimulus-rails are continuously being updated for changes that take place here. The best way to see the current big picture is to make a new rails app and install the importmap-rails and hotwire-rails gems to see the setup you get at that point. And from what I understand, to get everything working properly you should run rails from github rails main. I had to revert my commits and stay on the pre-importmap versions of the gems for now.

**Comment by shafy** [comment]
Thanks. Closing this issue for now as it's expected behavior.
