### ISSUE TITLE
What is the recommended way to import css bundled in js libraries

### ISSUE THREAD

**Issue by jean-francois-labbe** [rails/importmap-rails#80]
When trying to use [glide.js](https://github.com/glidejs/glide) with importmap.
Glide.js provides a js and a css file.

importmap-rails provides a way to vendor the js.
```sh
➜ bin/importmap pin @glidejs/glide --download
Pinning "@glidejs/glide" to vendor/javascript/@glidejs/glide.js via download from https://ga.jspm.io/npm:@glidejs/glide@3.5.2/dist/glide.esm.js
```
We don't know what is the best way to include the css.
We found a way to include the css by using the package.json.
The problem is that the glide.js dependency version is in 2 places that must be kept in sync.

Downloading vendor files from the JavaScript CDN
_package.json_
```json
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@glidejs/glide": "^3.5.2",
  }
}
```

I'm wondering if it could be useful to automatically/optionnaly vendor the css when downloading the js ?
```sh
bin/importmap pin @glidejs/glide --download --download-css
```

**Comment by dhh** [comment]
Yeah, you'll have to do this by hand. We don't have an API that could figure out what assets might be needed in addition to the main JS file. There may well be more than one. There may well be images. I don't see a path of us programmatically figuring this out.

**Comment by buncis** [comment]
to do it manually meaning is to do these steps

1. download the css file manually
2. put it on your `vendor` directory
3. then require the file to your `app/assets/stylesheets/application.css`

**Comment by dacook** [comment]
It seems really weird to me that the importmap solution doesn't cover css. It's like it only does half the job and leaves you to wonder about the rest (a google search shows lots of people scratching their heads and generally reverting to bundling).

When trying to migrate to import maps, the first thing I expected to see is extra options like this:

```ruby
pin "tom-select", to: "https://ga.jspm.io/npm:tom-select@2.2.2", preload: true,
  javascript: "/dist/js/tom-select.complete.js",
  css: "/dist/css/tom-select.css"
```

**Comment by dacook** [comment]
I wasn't able to find a solution, so for the interim I've just been using HTML tags directly in a partial:

```html
<!-- Load tom-select from CDN -->
<script src="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/js/tom-select.complete.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.min.css" rel="stylesheet">
```

To me, this seems superior because the package config is all in one place (name, version and entry point).

**Comment by buncis** [comment]
did you render the partial on <head> or <body>?

**Comment by dacook** [comment]
@buncis I'm not sure what you mean. This partial is rendered on all pages in my application (which is ok because it's used on most).

**Comment by buncis** [comment]
I press enter when all my typing is not inputted (wireless keyboard on linux XD)

have updated it

oh it is because html safe from github maybe

**Comment by dacook** [comment]
Thanks, I've updated my answer too, to help keep commit history concise.

**Comment by SlimGee** [comment]
has this been solved, checking after 2 years
