### ISSUE TITLE
Bootstrap not working

### ISSUE THREAD

**Issue by omairrazam** [rails/importmap-rails#83]
//importmap.rb
`pin "jquery", to: 'https://code.jquery.com/jquery-3.2.1.slim.min.js'

pin "popper", to: 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js'

pin "bootstrap", to: 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js'`

//application.js
`import "jquery"
 import "bootstrap"
`
It seems like `this` is undefined when loading library in importmap ecosystem.

<img width="660" alt="Screenshot 2021-12-11 at 3 41 24 AM" src="https://user-images.githubusercontent.com/10624816/145650397-5f69f096-6b10-4b8a-922a-ae392ed6d6d9.png">

**Comment by guybedford** [comment]
@omairrazam Bootstrap as imported there is a "script" not a "module". In modules, the `this` binding is not the global object but undefined, so `this.bootstrap = Bootstrap` fails.

Either load that file as a script, or use a version of Bootstrap that works as a module. For example via a module CDN which can handle this conversion process.

**Comment by ianneub** [comment]
@omairrazam I had some issues getting bootstrap and popper working with Rails 7.0.0.alpha2, finally fixed them by changing the relevant entries in `./config/importmap.rb` to:
```
pin "bootstrap", to: "https://ga.jspm.io/npm:bootstrap@5.1.3/dist/js/bootstrap.esm.js"
pin "@popperjs/core", to: "https://ga.jspm.io/npm:@popperjs/core@2.11.0/dist/esm/index.js"
```

**Comment by bensheldon** [comment]
@ianneub Do dropdowns work when you import the `esm` version of Bootstrap? I am only successful when pinning the bundle version that includes Popper, e.g.:

```ruby
pin "bootstrap", to: "https://ga.jspm.io/npm:bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
```

[Bootstrap's docs seem to imply that the dropdowns don't work for the esm version](https://getbootstrap.com/docs/5.0/getting-started/javascript/#using-bootstrap-as-a-module):

> Due to browser limitations, some of our plugins, namely Dropdown, Tooltip and Popover plugins, cannot be used in a <script> tag with module type because they depend on Popper. For more information about the issue see [here](https://v8.dev/features/modules#specifiers).
