### ISSUE TITLE
Possible issue shim not honoring config.assets.prefix

### ISSUE THREAD

**Issue by rromanchuk** [rails/importmap-rails#89]
As i'm bumbling around on development i'm trying to get the most verbose and most production-like set up so i can better understand the working parts i'm running `bin/rails assets:precompile` with `config.assets.prefix = "/dev-assets"` 

On page load i'm getting a bad route
```
devlog        | ActionController::RoutingError (No route matches [GET] "/assets/es-module-shims.js-2cdffbe3452e6a89e4b5e919cfb60b544a5ef6d45f21d93df54c4af2a76890bc.map"):

```

Sprockets did write it to `public/dev-assets/es-module-shims.js-2cdffbe3452e6a89e4b5e919cfb60b544a5ef6d45f21d93df54c4af2a76890bc.map` so 

The actual mappings look good 
```
// bin/importmap json
{
  "imports": {
    "application": "/dev-assets/application-93ee4e955b86e96387d3aa9cc90658c164fefd765c992f79d37b72fdd09c1d0f.js",
    "@hotwired/turbo-rails": "/dev-assets/turbo.min-2e35750e215200b3e20412a6fa49c166604997c83c17a063885c0e06c5c5c0fe.js",
    "@hotwired/stimulus": "/dev-assets/stimulus.min-471bff773ecece7e73ba136dfdf213f54a5b6ef32de7df8863280be2bfc7c0c4.js",
    "@hotwired/stimulus-loading": "/dev-assets/stimulus-loading-c1cc576b2c58baf36b1e1f81e8f4265e3023b9b322711c18f26d270f6bdf26b0.js",
    "firebase/app": "https://www.gstatic.com/firebasejs/9.6.1/firebase-app.js",
    "firebase/auth": "https://www.gstatic.com/firebasejs/9.6.1/firebase-auth.js",
    "firebase/analytics": "https://www.gstatic.com/firebasejs/9.6.1/firebase-analytics.js",
    "firebase/app-check": "https://www.gstatic.com/firebasejs/9.6.1/firebase-app-check.js",
    "@fortawesome/fontawesome-free": "https://ga.jspm.io/npm:@fortawesome/fontawesome-free@5.15.4/js/fontawesome.js",
    "@fortawesome/fontawesome-svg-core": "https://ga.jspm.io/npm:@fortawesome/fontawesome-svg-core@1.2.36/index.es.js",
    // [clipped]
}
```

**Comment by rromanchuk** [comment]
Actually, helper tag looks fine. This is probably reload/browser cruft or missing `touch tmp/restart.txt` 

`<script src="/dev-assets/es-module-shims.min-064d3375656d4550e01a95cfeb330fb651e5e053fd3a694691aa131870e7f307.js" async="async" data-turbo-track="reload"></script>`

I'll poke around more

**Comment by ollie-nye** [comment]
> Actually, helper tag looks fine. This is probably reload/browser cruft or missing `touch tmp/restart.txt`
> 
> `<script src="/dev-assets/es-module-shims.min-064d3375656d4550e01a95cfeb330fb651e5e053fd3a694691aa131870e7f307.js" async="async" data-turbo-track="reload"></script>`
> 
> I'll poke around more

Hi @rromanchuk, do you know what you did to get the helper tag to reflect the importmap? I'm seeing the same issue, the importmap has the correct prefix but the helpertag still uses `/assets` as the prefix
