### ISSUE TITLE
Rails new application starting issue.

### ISSUE THREAD

**Issue by Yashk626** [rails/importmap-rails#93]
While creating new application i am facing issue with importmap can anyone please explain how to resolve this issue please check below  error 

Bundle complete! 15 Gemfile dependencies, 70 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  importmap:install
rails aborted!
TZInfo::DataSourceNotFound: tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install
C:/Users/nittr/desktop/Ruby/newBlog/config/environment.rb:5:in `<main>'

Caused by:
TZInfo::DataSources::ZoneinfoDirectoryNotFound: None of the paths included in TZInfo::DataSources::ZoneinfoDataSource.search_path are valid zoneinfo directories.
C:/Users/nittr/desktop/Ruby/newBlog/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
       rails  turbo:install stimulus:install
You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem.
You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem.

**Comment by philr** [comment]
See also tzinfo/tzinfo#128.
