### ISSUE TITLE
JavaScript for different environments?

### ISSUE THREAD

**Issue by phaedryx** [rails/importmap-rails#94]
In the Rails app we are using where I work we have multiple per-environment files:
```
- config
   |- webpack
      |- development.js
      |- environment.js
      |- production.js
      |- staging.js
      |- test.js
```

One of the reasons we do this is that there are libraries that are useful for development that we don't want to be part of production. Another is to have environment-specific versions of a library used for that environment.

Is there a way to do this with `importmap-rails` that I have missed?

It might be nice to have groupings like Gemfiles, e.g.

```ruby
# bin/importmap pin react --env development --group development
# bin/importmap pin react --group production

# importmap.rb

group :development do
  pin "react", to: "https://ga.jspm.io/npm:react@17.0.2/dev.index.js"
end

group :production do
  pin "react", to: "https://ga.jspm.io/npm:react@17.0.2/index.js"
end


```

**Comment by jmckible** [comment]
You may want to take a look at #69 as a proposal for supporting multiple map definitions. I've got an up-to-date fork [@vocalvideo/importmap-rails](https://github.com/vocalvideo/importmap-rails). You could define a different map for each environment and dynamically include in your layout with `javascript_importmap_tags map: Rails.env`

I've also wondered about using environment variables (see #97). For now I'm using a meta tag to allow for branching in code.

**Comment by dhh** [comment]
Remember that this file is just Ruby! So you could do: `pin "react", to: "https://ga.jspm.io/npm:react@17.0.2/#{"dev." if Rails.env.development?}index.js"`

**Comment by dhh** [comment]
Or even do the blocks fully:

```ruby
if Rails.env.development?
  pin ..
  pin ..
else
  pin ..
  pin ..
end
```

I don't think there's enough here to warrant extensions to the DSL at the moment.

**Comment by phaedryx** [comment]
fair enough
