### ISSUE TITLE
Best Practice for Environment Variables

### ISSUE THREAD

**Issue by jmckible** [rails/importmap-rails#97]
With webpacker, we were able to define environment variables in `process.env`. We used it to store things like `RAILS_ENV` or keys for Stripe integration.

Is there are recommended way to achieve the same result with importmap? My first thought is to define a meta tag, but is there another approach?

**Comment by guybedford** [comment]
@jmckible `process.env` is a CommonJS specific feature, and the `process` global isn't available in browsers.

Simply defining globals is one option - `globalThis.RAILS_ENV = ...` - they are exactly the shared global state.

There have been discussions around custom namespaces here like a `import.meta.env` dictionary or similar, but this is just hypothetical and there are currently no standards or common conventions for environment variables in both Node.js and the browser, short of the global.

**Comment by jmckible** [comment]
@guybedford Thanks, it sounds like I'm not missing anything obvious. I'll continue to set meta tags for `Rails.env` and relevant `Rails.application.config` values until I come across something better.

And to document some use cases for others searching:

1. Stripe Publishable keys to differentiate production from test
2. Error reporting based on environment
3. Tagging releases for Sentry monitoring
4. Access to canonical host names based on environment
